CREATE TABLE IF NOT EXISTS `IT202_S24_Pokemon` (
    `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `base_experience` INT NOT NULL,
    `name` VARCHAR(100) NOT NULL UNIQUE,
    `weight` DECIMAL(10,2) NOT NULL,  
    `created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `modified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
